---
title: "Calculate MSCI for specific traits and combinations"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Set up
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
opts_knit$set(root.dir = here::here())

conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)
conflicted::conflicts_prefer(stats::lag)
conflicted::conflicts_prefer(brms::ar)
conflicted::conflicts_prefer(brms::dstudent_t)
conflicted::conflicts_prefer(brms::pstudent_t)
conflicted::conflicts_prefer(brms::qstudent_t)
conflicted::conflicts_prefer(brms::rstudent_t)

# Packages
library(tidyverse)
library(brms)
library(tidybayes)

# Source
source(here("source", "summarise_brms_models.R"))
```

# Goal

Fit models and calculate MSCI for specific trait combinations.

# Load data

```{r}
data_path <- file.path("data", "processed")

species_traits_final <- read_csv(file.path(data_path,
                                           "prop_data_per_trait.csv"))
```

# Automatisation

-   Make a list with each trait (combination)
-   `lapply()` to create list of filtered dataframes
-   `lapply()` to create formula list
-   fit models in for loop
-   check MCMC convergence in for loop
-   check model fit in for loop
-   ...
