---
title: "Data preparation"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
bibliography: [references.json]
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
---

```{r setup, include=FALSE}
# Set up
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE)
opts_knit$set(root.dir = here::here())

conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)

# Packages
library(tidyverse)
```

# Goal

# Load data

We read in the data and prepare it for further processing. We select stationary and migratory species.

```{r}
data_path <- file.path("data", "raw")

# Species list
check_list_flanders <- read_delim(
    file.path(data_path, "tblChecklistFlanders.csv"),
    delim = ";") %>% 
  filter(Status == "Standvlinder" | Status == "Trekvlinder") %>% 
  select(species_nl)

# Presences
presence_data <- read_delim(
    file.path(data_path, "tblAllCondensUtm5km_v2022.csv"),
    delim = ";")
```

