---
title: "Data exploration"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
bibliography: [references.json]
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
---

```{r setup, include=FALSE}
# Set up
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
opts_knit$set(root.dir = here::here())

conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)

# Packages
library(tidyverse)
```

# Goal

Exploration of the data. Where are the bottlenecks? Missing data? ...

# Load data

```{r}
out_path <- file.path("data", "processed")

species_traits_final_nozero <- read_csv(
  file.path(out_path, "prop_data_per_trait_nozero.csv")
)
species_traits_final <- read_csv(file.path(out_path, "prop_data_per_trait.csv"))
```

# Missing data and duplicates

We do not know all the traits for the following species.

```{r}
species_traits_final %>% 
  filter(is.na(trait_value)) %>%
  distinct(species_nl, trait_name) %>%
  mutate(val = 1) %>%
  pivot_wider(names_from = trait_name, values_from = val) %>%
  mutate(across(-c(species_nl), ~replace(.x, .x == 1, cur_column()))) %>%
  unite("trait_name", -c(species_nl), sep = ", ", na.rm = TRUE) %>%
  kable()
```

Some species occur for more than one trait value within the same trait.

```{r}
species_traits_final %>%
  count(species_nl, period, trait_name) %>%
  filter(n > 1) %>%
  distinct(species_nl, trait_name) %>%
  inner_join(distinct(species_traits_final, species_nl, trait_name, trait_value), 
             by = join_by(species_nl, trait_name)) %>%
  kable()
```



